### PR TITLE
move application to LFS

### PR DESCRIPTION
**Pull request by heythisisnate**
A relatively new feature called [Lua Flash Store (LFS) ](https://nodemcu.readthedocs.io/en/latest/lfs/) allows us to save a bunch of heap memory by moving the Konnected application code to flash storage.

### CODE REVIEW

**Comment by qu3bec** [comment]
How to get this update/feature?

**Comment by heythisisnate** [comment]
@qu3bec flash the 2.2.7 firmware & filesystem files from here: https://github.com/konnected-io/konnected-security/tree/master/firmware

**Comment by qu3bec** [comment]
Just flashed board won't boot, esplorer shows Can't auto detect firmware and then some weird characters keep typing on esplorer scree,

**Comment by heythisisnate** [comment]
@qu3bec try flashing with the command line script. I may need to update the Konnected Flash Tool. Will look into it today. 
https://github.com/konnected-io/konnected-security/blob/master/scripts/flash

**Comment by qu3bec** [comment]
With command line no light at all on board unless I’m doing something wrong. Couldn’t figure out how to use your executable script so flashed manually using command line both files. How to use your executable script?

**Comment by heythisisnate** [comment]
@qu3bec are you using windows or Mac?
I've updated the flash tool for Mac here: https://s3.us-east-2.amazonaws.com/konnected-io/Konnected-Flash-Tool-3.1.dmg
Windows version update is still in the works

**Comment by qu3bec** [comment]
@heythisisnate Windows. I manage to flash it us By command line but just noticed that there is a new commit to filesytem file and it’s not lot smaller in size compared to 1000KB I downloaded earlier. Why the big change in file size? Should I flash again with the new file?

**Pull request merged**
