### PR TITLE
Add support for typical key switch with relay

### PR DESCRIPTION
**Pull request by tailg8nj**
So this is my first foray into Konnected and SmartThings so please bear with me if the code needs tests or the tiles are ugly.

This device handler successfully controls my Vista 20P key switch. I set my system up similar to Dave Parsons in https://help.konnected.io/support/discussions/topics/32000001630.

This handler can handle both a "push" and a "hold" of the button to produce two different momentary delays, in my case 1000ms and 3000ms.

Please let me know what I need to do to get this acceptable

### CODE REVIEW

**Comment by heythisisnate** [comment]
Thanks for the contribution! This is great.
I didn't know that the key switch on the Vista had two different functions based on timing. Neat!

The code looks pretty good ... but why the icon of the remote control?
Is the 1s/3s keyswitch a standard thing for all the Vista panels? Maybe it makes more sense to make it specific to that and name the buttons "Arm Stay" and "Arm Away" instead. What do you think?

**Comment by tailg8nj** [comment]
The 1s/3s is standard at least across Vista 15 & 20: http://library.ademconet.com/MWT/fs2/9/1005.pdf.

I've made the updates requested. However when I look at SmartThings doc it says Button capability is deprecated. I'll look to see if I can switch this to Momentary.

**Comment by tailg8nj** [comment]
Now that I've specialized it to be Vista specific, I'm wondering if I should further customize it to use the proper SmartThings Button state values, and also modify the tiles to show correctly with the alarm status. I would need access to other pin states. is that possible via an API call?

**Comment by tailg8nj** [comment]
Closing in favor of https://github.com/tailg8nj/konnected-vista-integrations

**Pull request closed without merging**
