### PR TITLE
Adding Konnected Water leak sensor

### PR DESCRIPTION
**Pull request by dpaquette**
I managed to get my wired water leak sensor working by adding a new device type. It correctly reports Wet / Dry state and works with Smart Home Monitor.

The only thing I don't have working right is the status icons. I can't find any documentation on where smart things has hidden the Wet / Dry icons.

## Device Status
Wet / Dry State

## Smart Home Monitor
Smart Home Monitor Alert

Smart Home Monitor Alert

## My Sensor

img_20170930_073147

### CODE REVIEW

**Comment by vseven** [comment]
Just look at a existing leak sensor like the SmartSense one: https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/smartsense-moisture-sensor.src/smartsense-moisture-sensor.groovy

and you'll see this:

```
		multiAttributeTile(name: "water", type: "generic", width: 6, height: 4) {
			tileAttribute("device.water", key: "PRIMARY_CONTROL") {
				attributeState "dry", label: "Dry", icon: "st.alarm.water.dry", backgroundColor: "#ffffff"
				attributeState "wet", label: "Wet", icon: "st.alarm.water.wet", backgroundColor: "#00A0DC"
			}
}
```

The problem is it really shouldn't be a device.contact like you have in your code, it should be device.water which will show the icons correctly.  But I'm not sure if that will work with Nates framework.

The correct thing to do would be for @heythisisnate to add a office "Water Sensor" type to the actual code that operates like the standard contact closure but has the code like you do sending the SendEvent to the water capability.  I don't think it will operate fully correctly until thats done.

**Comment by dpaquette** [comment]
Thanks @vseven 

It does work currently. I will give it a try with `device.water` to see if it still works. I will give that a try later tonight and report work.

**Comment by vseven** [comment]
I'm sure it works, and it may work because of the way Nate is sending status updates (the 0 or 1).  In a normal device you'd send a name (like "water") and a value to the device handler so it can handle multiple capabilities.  All the Konnected device types only really have the one capability so the way they are programmed he only sends a single value which is assumed to be the value for the device which as you see then gets converted into the send value.

Switching your tile to device.water along with adding the icons should fix your issue.

I said correct thing to do is add it to the code as a water sensor is so the device gets auto created when you assign "water sensor" to a pin.  Right now it can never be created....it has to be set to a contact sensor, created, then the device handler manually changed.

**Comment by dpaquette** [comment]
Oh I see. I had originally created it as a contact sensor so that explains why it worked for me

**Comment by dpaquette** [comment]
Thanks @vseven . I made those changes, removed the device and readded it and everything seems to be working now.


screenshot_2017-11-18-19-15-00

**Comment by dpaquette** [comment]
Some additional info for @heythisisnate 

I can't say for certain because this sensor was in the house when we bought it but I think this is the sensor https://www.aartech.ca/gri2800-goerge-risk-water-sensor.html

**Comment by vseven** [comment]
Yeah, I bought a couple that look just like that pretty cheap on eBay that worked fine for like $9 each that I was using on another controls system.

**Comment by heythisisnate** [comment]
At quick glance this looks great. I'll test soon it and merge it as long as everything is good. 
Thank you @dpaquette and @vseven !

**Comment by heythisisnate** [comment]
Thanks again for the contribution, @dpaquette. I'm glad this works for you. I'm a little surprised because the specs for the sensor that you linked to says it requires a minimum of 5V, but the NodeMCU output is only 3.3V. I guess it's close enough!

**Comment by dpaquette** [comment]
Yeah I was a little surprised too but it does work. I ordered another sensor so we'll see if the new one works too

**Pull request merged**
